---
subtitle: "Rapport statistique V0.9"
cache: false
---


```{r}
#| label: setup

rm(list = ls())
#
library(baseph)
library(tidyverse)
library(gtsummary)
library(kableExtra)
library("forestmodel")
library(labelled)
library(epiDisplay)
library(visdat)
library(corrplot)
library(biostats)
library("colorspace")
library("apyramid")
library("FactoMineR")
library("factoextra")
library("missMDA")
library("readODS")
library("ggsci")
library("survival")
library("survminer")
#
  load("datas/cavithy.RData")
expx <- FALSE
classeur <- "cavithy_v01.ods"
# if (exp){system(paste0("rm -f ",classeur))}
#
ptest <- list(all_continuous() ~ "t.test", all_categorical() ~ "chisq.test")
stt <- list(
  all_continuous() ~ "{mean} ± {sd}",
  all_categorical() ~ "{n}/{N} ({p}%)"
)
```

\bigskip

\begin{notebox}[Attention !]
Pour toutes les variables binaire (oui/non), seul le code "`Oui`" est présenté dans la plupart des tableaux.
\end{notebox}


# Validation de la population

## Données manquantes

```{r}
#| label: fig-manq1
#| fig-cap: missing data
#| fig-asp: 1


vis_dat(tt[,6:33],
         sort_type = FALSE,
          warn_large_data = FALSE) +
  labs(title = "Missing data") +
    theme(
    legend.position = "bottom",
    axis.text.x = element_text(angle = 70, vjust =0, hjust=0)
  )
```
